### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by sandersch** [matt-lowe/ProfanityFE#3]
Are you still actively developing this? Is this the latest version of the code? 

I have been using Profanity as my primary frontend since about the beginning of the year and it works pretty well for me in general and fits my workflow much better than the Wizard or Stormfront. There are a few things I would like to help improve (e.g. add some more macro features, fixing puts/print output going to the terminal instead of the frontend), but I wanted to make sure this repo is a good starting point before I started any major rocket surgery.

**Comment by vatic42** [comment]
Hi Charlie -- I've also been using it as my primary frontend for the last
couple years.  Works great.  :)  If you send patches I'll merge them.

**Comment by sandersch** [comment]
Sweet! I played around with it a couple years ago and then took a break from the game. Came back a little bit ago and was using the Wizard again but switched over to Profanity inside tmux recently and love it. Regex highlights are so awesome.
